### ISSUE TITLE
Cut 0.9.3 QPC CLI Release

### ISSUE THREAD

**Issue by kholdaway** [quipucords/qpc#150]
## Feature description:

Cut 0.9.3 QPC CLI Release

**Comment by myersCody** [comment]
# Features
- [Issue 152](https://github.com/quipucords/qpc/issues/152) - CLI expose feature to mask Hostname, IP Address, and Mac address
- [Issue 148](https://github.com/quipucords/qpc/issues/148) - Expose endpoint to upload a details report (to unblock engagements)
- [Issue 145](https://github.com/quipucords/qpc/issues/145) - Added password arg to server login
- [PR 144](https://github.com/quipucords/qpc/pull/144) - Bump version to 0.9.3
# Bugs
- Improvements in the manpage accuracy

**Comment by myersCody** [comment]
Prerelease Added: https://github.com/quipucords/qpc/releases/tag/0.9.3
