### ISSUE TITLE
Modify qpc insights upload from local json to take in a directory instead of json

### ISSUE THREAD

**Issue by abaiken** [quipucords/qpc#95]
## Feature description:
A local json file will no longer be possible because an insights report will be comprised of a metadata payload & one or more report payloads. We should take in a directory instead. 

### Is your feature request related to a problem?
Insights reports can be very large. Additionally, we can't validate a report without loading the JSON. The act of loading a very large JSON file could cause our service to have memory issues.

Since we  are sending a tar.gz to the file upload service, we should split out the metadata into a small JSON payload that will always load and a report JSON payload (possibly multiple report payloads).

### Describe the solution you'd like
The details still need to be worked out but I wanted to capture it regardless. 

___

## Acceptance Criteria:

- [ ] Verify that qpc insights upload takes a directory instead of a file

**Comment by kholdaway** [comment]
Decided not to implement.
